import { generateText, isStepCount } from 'ai';
import { getAgentModel } from './providers';
import { buildAgentTools } from './tools';
import { getBinanceAdapter } from '@/lib/binance-mcp';
import { ARGUS_SYSTEM_PROMPT, FIRST_TURN_SESSION_TITLE_DIRECTIVE } from './prompts';
import type { AgentOptions, AgentResult, ExecutedToolCall } from './types';

/**
 * Executes the core Argus Agent reasoning and tool-calling loop
 * 
 * @param options - Prompt, context, history, execution mode, and optional API overrides
 * @returns Structured AgentResult with text analysis and tool telemetry
 */
export async function executeAgent(options: AgentOptions): Promise<AgentResult> {
  const {
    prompt,
    symbol,
    mode = 'simulation',
    modelName,
    apiKey,
    history = [],
    maxSteps = 5,
    isFirstTurn,
    systemDirective,
  } = options;

  // 1. Initialize the adapter and bind Binance MCP tools
  const adapter = getBinanceAdapter(mode);
  const tools = buildAgentTools(adapter);

  // 2. Obtain Groq model instance
  const model = getAgentModel(modelName, apiKey);

  // 3. Construct user prompt with optional pair context
  const currentUserPrompt = symbol
    ? `[Pair Context: ${symbol.toUpperCase()}]\nUser: ${prompt}`
    : prompt;

  // 4. Assemble system prompt with autonomous session titling directive on first turn
  const effectiveIsFirstTurn = isFirstTurn ?? (!history || history.length === 0);
  const directives: string[] = [];
  if (effectiveIsFirstTurn) {
    directives.push(FIRST_TURN_SESSION_TITLE_DIRECTIVE);
  }
  if (systemDirective) {
    directives.push(systemDirective);
  }

  const effectiveSystemPrompt = directives.length > 0
    ? `${ARGUS_SYSTEM_PROMPT}\n\n${directives.join('\n\n')}`
    : ARGUS_SYSTEM_PROMPT;

  // 5. Run autonomous agent loop with multi-step tool-calling
  const generateParams = history && history.length > 0
    ? {
        model,
        system: effectiveSystemPrompt,
        messages: [
          ...history.slice(-10).map((h) => ({
            role: h.role,
            content: h.content,
          })),
          {
            role: 'user' as const,
            content: currentUserPrompt,
          },
        ],
        tools,
        stopWhen: isStepCount(maxSteps),
      }
    : {
        model,
        system: effectiveSystemPrompt,
        prompt: currentUserPrompt,
        tools,
        stopWhen: isStepCount(maxSteps),
      };

  const { text, steps } = await generateText(generateParams);

  // 6. Extract session title if generated by the agent on first turn
  // Search in final text, or across intermediate step texts if tool calling preceded text
  const stepTexts = steps
    .map((s) => s.text)
    .filter((t): t is string => typeof t === 'string' && t.trim().length > 0)
    .join('\n');
  const candidateText = `${stepTexts}\n${text}`;
  const titleMatch = candidateText.match(/<session_title>([\s\S]*?)<\/session_title>/i);

  // Clean title: trim whitespace and surrounding quotes/backticks
  const rawTitle = titleMatch ? titleMatch[1].trim() : undefined;
  const sessionTitle = rawTitle
    ? rawTitle.replace(/^["'`]+|["'`]+$/g, '').trim()
    : undefined;

  // Clean analysis text: remove all session_title tags with global regex
  let cleanedAnalysis = text.replace(/<session_title>[\s\S]*?<\/session_title>\s*/gi, '').trim();

  // If the agent only output the session title tag and no additional commentary,
  // provide a natural acknowledgement fallback instead of an empty bubble
  if (!cleanedAnalysis && sessionTitle) {
    cleanedAnalysis = `Started a new chat for **${sessionTitle}**. How can I help you today?`;
  }

  // 7. Extract executed tool calls and telemetry from all completed steps
  const executedToolCalls: ExecutedToolCall[] = [];
  for (const step of steps) {
    if (step.toolCalls && step.toolCalls.length > 0) {
      for (const call of step.toolCalls) {
        const resultItem = step.toolResults?.find(
          (r) => r.toolCallId === call.toolCallId
        );
        executedToolCalls.push({
          toolName: call.toolName,
          args: (call.input as Record<string, unknown>) ?? {},
          result: resultItem ? resultItem.output : undefined,
        });
      }
    }
  }

  return {
    symbol: symbol?.toUpperCase(),
    sessionTitle,
    analysis: cleanedAnalysis,
    toolCalls: executedToolCalls,
    stepCount: steps.length,
    executionMode: mode,
    timestamp: Date.now(),
  };
}

// Convenient alias
export const runAgent = executeAgent;
export const runArgusAgent = executeAgent;
