/**
 * Centralized Application UI Copy and Labels
 * 
 * Enforces Rule 1 (Zero hardcoded text in components/controllers)
 * and Rule 5 (Clean, organized, well-commented code).
 */

export const APP_CONTENT = {
  sidebar: {
    brand: 'Argus',
    subtitle: 'Binance Agent OS',
    badge: 'Track A',
    newChat: 'New Chat',
    newChatDisabled: 'Current chat is already new',
    viewsTitle: 'Workspace Views',
    agentView: 'Agent Chat',
    chartView: 'Trading Chart',
    globalView: 'Global Workspace',
    globalViewTooltip: 'Open workspace not tied to any symbol',
    historyTitle: 'Saved Conversations',
    emptyHistory: 'No conversations yet',
    workspaceGroupsTitle: 'Active Workspaces',
    emptyWorkspaces: 'No symbol workspaces yet',
    globalWorkspaceGroup: 'Global Market',
    newChatInSymbolTooltip: (symbol: string) => `Start new chat in #${symbol}`,
    chatsCount: (count: number) => `${count} ${count === 1 ? 'chat' : 'chats'}`,
    statusOnline: 'Live Binance Feeds',
    themeLight: 'Light Mode',
    themeDark: 'Dark Mode',
    themeLightBadge: 'LIGHT',
    themeDarkBadge: 'DARK',
    collapseSidebar: 'Collapse sidebar',
    expandSidebar: 'Expand sidebar',
    deleteChat: 'Delete Chat',
    renameChat: 'Rename Chat',
    deleteDialogTitle: 'Delete Conversation',
    deleteDialogDescription: (title?: string) =>
      title
        ? `Are you sure you want to delete "${title}"? All messages and market research from this chat will be permanently removed.`
        : 'Are you sure you want to delete this conversation? All messages and market research will be permanently removed.',
    deleteDialogConfirm: 'Delete Chat',
    deleteDialogCancel: 'Cancel',
  },
  header: {
    brand: 'ARGUS // BINANCE AGENT OS',
    title: 'Argus',
    subtitle: 'Trading assistant powered by Binance Agent OS',
    badge: 'Binance Agent OS',
    hackathonTrack: 'Track A',
    publicFeedsActive: 'Live Binance Feeds',
    inferenceActive: 'AI Online',
  },
  nav: {
    brandMonogram: 'A.',
    brandTooltip: 'Argus Trading Assistant',
    searchPlaceholder: 'Search markets, pairs, or agent tools...',
    searchTooltip: 'Search markets',
    notificationsTitle: 'Market Alerts',
    notificationsCount: '3',
    statusOnline: 'Live Feeds Active',
    themeToggleDark: 'Switch to light theme',
    themeToggleLight: 'Switch to dark theme',
    items: {
      dashboard: 'Dashboard',
      wallet: 'Wallet',
      alerts: 'Signals',
      reports: 'Analysis',
      analytics: 'Analytics',
    },
  },
  stage: {
    category: 'Market Overview',
    defaultSymbol: 'BTC / USDT',
    defaultSubtitle: 'Binance Spot • Real-time Feeds & Agent Reasoner',
    switcher: {
      agent: 'Agent',
      chart: 'Chart',
    },
  },
  cards: {
    account: {
      title: 'Account & Portfolio',
      badge: 'Coming Soon',
      emptyTitle: 'Wallet & Balances',
      emptySubtitle: 'Live Binance wallet balances and paper trading asset metrics will be displayed here.',
    },
    activeTrades: {
      title: 'Active Trades',
      badge: 'Coming Soon',
      emptyTitle: 'Order Book & Executions',
      emptySubtitle: 'Live order book depth, taker flow, and active position metrics will be displayed here.',
    },
    marketAnalysis: {
      title: 'Daily Market Analysis',
      badge: 'Coming Soon',
      emptyTitle: 'Market Sentiment & Intelligence',
      emptySubtitle: 'Daily market overview, sentiment metrics, and Exa web search synthesis will be displayed here.',
    },
    chart: {
      title: 'Trading Chart',
      badge: 'Interactive View',
      emptyTitle: 'Trading Chart Integration',
      emptySubtitle: 'Interactive real-time candlestick charts and technical indicator overlays will be available here.',
      switchHint: 'Switch back to the Agent view to interact with live Binance feeds and market analysis.',
    },
  },
  modes: {
    simulation: {
      label: 'Live Public Feeds',
      description: 'Stream and analyze real-time Binance spot and derivative market data with zero API keys.',
    },
  },
  chat: {
    title: 'Chat',
    subtitle: 'Ask questions, check prices, and inspect order books in real time',
    inputPlaceholder: 'Ask Argus...',
    sendButton: 'Send',
    stopButton: 'Stop generating',
    clearButton: 'Clear',
    emptyCategory: 'Binance Market Assistant',
    emptyTitle: 'How can I help you today?',
    emptySubtitle: 'Analyze live order books, check funding rates, and inspect 24h market stats with real-time Binance feeds.',
    quickActionsTitle: 'Quick Actions',
    quickActions: [
      { id: 'depth', label: 'BTC/USDT Depth', template: 'Check BTCUSDT live price, spread, and order book depth' },
      { id: 'stats', label: 'BTC 24h Stats', template: 'Show 24h market stats and volume for BTCUSDT' },
      { id: 'oi', label: 'BTC Funding & OI', template: 'Check BTCUSDT live open interest and funding rate' },
      { id: 'news', label: 'BTC News & Catalysts', template: 'Search latest crypto news, catalysts, and sentiment for BTC' },
    ],
    globalQuickActions: [
      { id: 'movers', label: 'Top Market Movers', template: 'What are the top crypto gainers and biggest market movers today across Binance?' },
      { id: 'news', label: 'Crypto Macro News', template: 'Search latest crypto macro news, regulatory catalysts, and protocol roadmaps' },
      { id: 'funding', label: 'Funding Comparison', template: 'Compare perpetual futures funding rates and open interest for BTC, ETH, and SOL' },
    ],
    getSymbolQuickActions: (symbol: string, baseAsset: string, quoteAsset?: string) => [
      {
        id: 'depth',
        label: quoteAsset ? `${baseAsset}/${quoteAsset} Depth` : `${baseAsset} Depth`,
        template: `Check ${symbol} live price, spread, and order book depth`,
      },
      {
        id: 'stats',
        label: `${baseAsset} 24h Stats`,
        template: `Show 24h market stats and volume for ${symbol}`,
      },
      {
        id: 'oi',
        label: `${baseAsset} Funding & OI`,
        template: `Check ${symbol} live open interest and funding rate`,
      },
      {
        id: 'news',
        label: `${baseAsset} News & Catalysts`,
        template: `Search latest crypto news, catalysts, and sentiment for ${baseAsset}`,
      },
    ],
    quickPromptsTitle: 'Quick Actions',
    quickPrompts: [
      'Check BTCUSDT live price, spread, and order book depth',
      'Show 24h market stats and volume for BTCUSDT',
      'Check BTCUSDT live open interest and funding rate',
      'Search latest crypto news, catalysts, and sentiment for BTC',
    ],
    toolCallsLabel: 'Tools used',
    toolCallsCountSuffix: 'tools used',
    viewDetails: 'Show details',
    hideDetails: 'Hide details',
    thinkingText: 'Checking live Binance market data...',
    userRole: 'You',
    agentRole: 'Argus',
    stepCountLabel: 'steps',
    errorNotice: 'Something went wrong while processing your request. Please check your Groq API key and connection.',
    newSessionButton: 'New Chat',
    newSessionDisabled: 'Current chat is already new',
    newChatButton: 'New Chat',
    newChatTooltip: 'Start a new conversation in this workspace',
    sessionsLabel: 'Chats',
    defaultSessionTitle: 'New Chat',
    defaultSessionTitles: ['Active Session', 'Market Research', 'New Chat', 'Chat', 'Active Chat'] as const,
    errorMessageTitle: 'Error',
    newSessionGreeting: (title: string) =>
      `Started a new chat for **${title}**. How can I help you today?`,
    workspaceBadge: 'WORKSPACE',
    globalWorkspaceTitle: 'Global Market',
    globalWorkspaceBadge: 'GLOBAL',
    globalWorkspaceSubtitle: 'Macro market research, cross-token analysis, and news uncoupled from any single symbol.',
    switchSymbolTooltip: 'Click to switch market workspace (⌘K)',
    followUpsTitle: 'Suggested Follow-ups',
    followUpAriaLabel: (question: string) => `Ask follow-up: ${question}`,
    fallbackFollowUps: (symbol: string) => [
      `Check ${symbol} order book depth and bid/ask liquidity walls`,
      `Inspect ${symbol} perpetual funding rate and long/short ratio`,
      `Search latest crypto news and catalysts affecting ${symbol}`,
    ],
    globalFallbackFollowUps: [
      'What are the top crypto gainers and biggest volume movers today across Binance?',
      'Compare perpetual futures funding rates across BTC, ETH, and SOL',
      'Search latest crypto regulatory news and macroeconomic market sentiment',
    ],
  },
  sessions: {
    menuTitle: 'Conversations',
    renameLabel: 'Rename',
    deleteLabel: 'Delete',
    saveLabel: 'Save',
    cancelLabel: 'Cancel',
    renamePlaceholder: 'Chat title...',
    emptyState: 'No conversations yet',
    activeBadge: 'ACTIVE',
    openMenuAria: 'Manage conversations',
    deleteDialogTitle: 'Delete Conversation',
    deleteDialogDescription: (title?: string) =>
      title
        ? `Are you sure you want to delete "${title}"? All messages and market research from this chat will be permanently removed.`
        : 'Are you sure you want to delete this conversation? All messages and market research will be permanently removed.',
    deleteDialogConfirm: 'Delete Chat',
    deleteDialogCancel: 'Cancel',
  },
  dialog: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    closeAria: 'Close dialog',
  },
  process: {
    title: 'Process',
    thinking: 'Thinking...',
    thinkingWithSeconds: (seconds: number) => `Thinking (${seconds}s)`,
    thoughtForDuration: (seconds: number) =>
      `Thought for ${seconds} ${seconds === 1 ? 'second' : 'seconds'}`,
    workingWithSeconds: (seconds: number) => `Working (${seconds}s)`,
    workedForDuration: (seconds: number) =>
      `Worked for ${seconds} ${seconds === 1 ? 'second' : 'seconds'}`,
    agentWorking: (seconds: number) => `Agent working (${seconds}s)`,
    intermediateUpdateLabel: 'Model update',
    analyzing: 'Analyzing market data...',
    generatingResponse: 'Generating response...',
    toolRunning: 'Running',
    toolCompleted: 'Completed',
    toolFailed: 'Failed',
    toolPrefix: 'Tool',
    stepsCompleted: 'steps completed',
    hideSteps: 'Hide process',
    showSteps: 'Show process',
    finalResponse: 'Final Response',
    thoughtForSteps: 'Thought for',
    reasonedFor: 'Reasoned for',
    thoughtProcess: 'Thought process',
    thinkingProcess: 'Thinking process...',
    thoughts: 'Thoughts',
    toolsUsedHeader: 'tools used',
    singleToolUsed: 'tool used',
    stepSuffix: 'steps',
    successBadge: 'Success',
    viewReasoning: 'View thoughts',
    hideReasoning: 'Hide thoughts',
    toolLabels: {
      get_ticker_price: (symbol?: string) =>
        symbol ? `Checking ${symbol} price` : 'Checking price',
      get_order_book: (symbol?: string) =>
        symbol ? `Inspecting ${symbol} order book depth` : 'Inspecting order book depth',
      get_klines: (symbol?: string, interval?: string) =>
        symbol && interval ? `Reading ${symbol} ${interval} chart` : symbol ? `Reading ${symbol} chart` : 'Reading chart',
      get_24h_stats: (symbol?: string) =>
        symbol ? `Fetching ${symbol} 24h market stats` : 'Fetching 24h market stats',
      get_funding_rate: (symbol?: string) =>
        symbol ? `Checking ${symbol} funding rate` : 'Checking funding rate',
      get_average_price: (symbol?: string) =>
        symbol ? `Calculating ${symbol} 5m average price` : 'Calculating average price',
      get_recent_trades: (symbol?: string) =>
        symbol ? `Reading ${symbol} recent trade tape` : 'Reading recent trades',
      get_open_interest: (symbol?: string) =>
        symbol ? `Checking ${symbol} open interest` : 'Checking open interest',
      get_global_long_short_ratio: (symbol?: string) =>
        symbol ? `Checking ${symbol} global long/short account ratio` : 'Checking global long/short account ratio',
      get_top_long_short_ratio: (symbol?: string) =>
        symbol ? `Checking ${symbol} top trader position ratio` : 'Checking top trader position ratio',
      search_crypto_news: (symbol?: string) =>
        symbol ? `Searching latest ${symbol} news & catalysts` : 'Searching crypto news & catalysts',
      default: (name: string) => name.replace(/_/g, ' '),
    },
    results: {
      actionSuccess: 'Action completed',
      livePrice: 'Live Price',
      fundingRate: 'Funding Rate',
      annualizedRate: 'Annualized (APR)',
      markPrice: 'Mark Price',
      indexPrice: 'Index Price',
      nextFunding: 'Next Settlement',
      averagePrice: '5m Avg Price',
      recentTrades: 'Recent Trades',
      tradeTime: 'Time',
      takerBuy: 'BUY',
      takerSell: 'SELL',
      buyPressure: 'Taker Buy Ratio',
      openInterest: 'Open Interest',
      openInterestContracts: 'Contracts',
      openInterestValue: 'Notional Value',
      openInterestTime: 'Updated',
      spread: 'Spread',
      spreadPercent: 'Spread %',
      bestBid: 'Best Bid',
      bestAsk: 'Best Ask',
      depthImbalance: 'Imbalance Ratio',
      topBids: 'Top Bids',
      topAsks: 'Top Asks',
      high24h: '24h High',
      low24h: '24h Low',
      change24h: '24h Change',
      volume24h: '24h Volume',
      timeframe: 'Timeframe',
      periodChange: 'Period Change',
      latestPrice: 'Latest Price',
      candlesCount: 'Candles Analyzed',
      newsResults: 'Web News & Catalysts',
      newsArticlesFound: 'Articles Found',
      newsSource: 'Source',
      newsDate: 'Date',
      newsOpenArticle: 'Read article',
      longShortRatio: 'Long/Short Ratio',
      longAccountRatio: 'Long Accounts',
      shortAccountRatio: 'Short Accounts',
      topLongRatio: 'Whale Longs',
      topShortRatio: 'Whale Shorts',
      retailSentiment: 'Account Sentiment',
      whaleSentiment: 'Whale Position Sentiment',
      bullishBias: 'BULLISH',
      bearishBias: 'BEARISH',
      neutralBias: 'NEUTRAL',
      period: 'Period',
      errorTitle: 'Action Error',
      emptyResult: 'No details available',
      priceHeader: 'Price',
      sizeHeader: 'Amount',
    },
    toolNames: {
      get_ticker_price: 'get_ticker_price',
      get_order_book: 'get_order_book',
      get_klines: 'get_klines',
      get_24h_stats: 'get_24h_stats',
      get_funding_rate: 'get_funding_rate',
      get_average_price: 'get_average_price',
      get_recent_trades: 'get_recent_trades',
      get_open_interest: 'get_open_interest',
      get_global_long_short_ratio: 'get_global_long_short_ratio',
      get_top_long_short_ratio: 'get_top_long_short_ratio',
      search_crypto_news: 'search_crypto_news',
    } as Record<string, string>,
  },
  symbolSearch: {
    buttonLabel: 'Search Markets',
    buttonAria: 'Search all Binance USDT markets',
    shortcut: '⌘K',
    shortcutWin: 'Ctrl+K',
    dialogTitle: 'Select Trading Pair',
    dialogSubtitle: 'Browse and switch between active Binance USDT spot markets',
    inputPlaceholder: 'Search pair (e.g. BTC, SOL, PEPE, SUI)...',
    activeBadge: 'ACTIVE',
    emptyTitle: 'No matching pairs found',
    emptySubtitle: 'Try searching with a different ticker or token name.',
    loading: 'Loading symbols...',
    errorMessage: 'Failed to load symbols from Binance API.',
    clearSearch: 'Clear search input',
    closeDialog: 'Close market search',
    marketsCount: (count: number) => `${count} USDT Markets`,
    pairsCount: (count: number) => `${count} pairs`,
    keyboardHint: 'ESC to exit • ↑↓ to navigate • ENTER to select',
    navLegend: '↑↓ navigate',
    selectLegend: '↵ select',
    escLegend: 'esc close',
    loadMoreHint: (remaining: number) => `Scroll down to load ${remaining} more pairs...`,
    showingCount: (visible: number, total: number) => `Showing ${visible} of ${total} pairs`,
  },
  marketPanel: {
    title: 'Market Overview',
    liveBadge: 'LIVE WS',
    streamRateTicker: '1000ms',
    streamRateDepth: '100ms',
    expandPanel: 'Show Market Panel',
    collapsePanel: 'Hide Market Panel',
    tickerTitle: 'Price & 24h Stats',
    orderBookTitle: 'Order Book Depth',
    high24h: '24h High',
    low24h: '24h Low',
    volume24h: '24h Volume',
    volumeQuote: '24h Quote Vol',
    priceChange: '24h Change',
    bestBid: 'Best Bid',
    bestAsk: 'Best Ask',
    spread: 'Spread',
    imbalance: 'Depth Imbalance',
    bids: 'Bids',
    asks: 'Asks',
    priceHeader: 'Price (USDT)',
    sizeHeader: 'Size',
    totalHeader: 'Total',
    bidsRatio: 'Bids',
    asksRatio: 'Asks',
    globalTitle: 'Global Market',
    globalEmptyNotice: 'Select a specific pair in the sidebar to inspect real-time order books and price ticks.',
    mockupNotice: 'Mockup Preview • Real Binance WebSocket connects in next phase',
  },
} as const;
