/**
 * Centralized Application UI Copy and Labels
 * 
 * Enforces Rule 1 (Zero hardcoded text in components/controllers)
 * and Rule 5 (Clean, organized, well-commented code).
 */

export const APP_CONTENT = {
  header: {
    brand: 'ARGUS // BINANCE AGENT OS',
    title: 'Argus',
    subtitle: 'Trading assistant powered by Binance Agent OS',
    badge: 'Binance Agent OS',
    hackathonTrack: 'Track A',
    mcpActive: 'MCP Connected',
    inferenceActive: 'AI Online',
  },
  nav: {
    brandMonogram: 'A.',
    brandTooltip: 'Argus Trading Assistant',
    searchPlaceholder: 'Search markets, pairs, or agent tools...',
    searchTooltip: 'Search markets',
    notificationsTitle: 'Market Alerts',
    notificationsCount: '3',
    statusOnline: 'Live Feeds Active',
    items: {
      dashboard: 'Dashboard',
      wallet: 'Wallet',
      alerts: 'Signals',
      reports: 'Analysis',
      analytics: 'Analytics',
    },
  },
  stage: {
    category: 'Market Overview',
    defaultSymbol: 'BTC / USDT',
    defaultSubtitle: 'Binance Spot • Real-time Feeds & Agent Reasoner',
    switcher: {
      agent: 'Agent',
      chart: 'Chart',
    },
  },
  cards: {
    account: {
      title: 'Total Portfolio',
      balanceUsd: '$10,240.00 USD',
      activeStatus: 'Sandbox Active',
      assetsCount: '4 active assets',
      demoAssets: [
        { symbol: 'USDT', amount: '5,000.00', usdValue: '$5,000.00' },
        { symbol: 'USDC', amount: '2,500.00', usdValue: '$2,500.00' },
        { symbol: 'BTC', amount: '0.0250', usdValue: '$1,685.50' },
        { symbol: 'SOL', amount: '7.4000', usdValue: '$1,054.50' },
      ],
      refreshLabel: 'Sync balance',
    },
    activeTrades: {
      title: 'Active Trades',
      velocityLabel: 'Order Book Depth Imbalance',
      ratioValue: '68.4%',
      bidsLabel: 'Bid Heavy',
      asksLabel: 'Ask Pressure',
      activeOrdersLabel: '2 Open Orders',
      pnlLabel: '+$240.50 (+2.4%)',
      recentTradesTitle: 'Recent Executions',
      trades: [
        { id: '1', pair: 'BTCUSDT', side: 'BUY', price: '$67,390.00', amount: '0.015 BTC', time: '1m ago' },
        { id: '2', pair: 'SOLUSDT', side: 'BUY', price: '$142.20', amount: '5.0 SOL', time: '6m ago' },
      ],
    },
    marketAnalysis: {
      title: 'Daily Market Analysis',
      sentimentScore: '72.7%',
      sentimentLabel: 'Greed / Bullish',
      sentimentSub: 'Market Trend',
      summary: 'BTC holding firmly above $66.8k support. Order book depth shows strong bid wall near $67,000.',
      keyLevels: 'Support: $66,800 • Resistance: $68,500',
      webSearchBadge: 'Exa Web Search Ready',
      sourcesLabel: 'Live Feeds & On-Chain Flow',
    },
    chart: {
      title: 'Trading Chart',
      badge: 'Coming Soon',
      emptyTitle: 'Trading Chart Integration',
      emptySubtitle: 'Interactive real-time candlestick charts and technical indicator overlays will be available here.',
      switchHint: 'Switch back to the Agent view to interact with live Binance feeds and market analysis.',
    },
  },
  modes: {
    simulation: {
      label: 'Sandbox',
      description: 'Practice with live Binance market data and a simulated balance.',
    },
    liveMcp: {
      label: 'Live Binance MCP',
      description: 'Connect directly to agent.binance.com/mcp/agentic via MCP.',
    },
  },
  chat: {
    title: 'Chat',
    subtitle: 'Ask questions, check prices, and inspect order books in real time',
    inputPlaceholder: 'Ask about prices, market trends, order book depth, or wallet balances...',
    sendButton: 'Send',
    clearButton: 'Clear',
    emptyTitle: 'How can I help you today?',
    emptySubtitle: 'Ask a question about the market or choose one of the suggestions below.',
    quickPromptsTitle: 'Suggestions',
    quickPrompts: [
      'Check SOLUSDT live price, spread, and order book depth',
      'Show 24h market stats and volume for BTCUSDT',
      'Check my demo wallet balances',
      'How is ETHUSDT looking on the 15m chart?',
    ],
    toolCallsLabel: 'Tools used',
    toolCallsCountSuffix: 'tools used',
    viewDetails: 'Show details',
    hideDetails: 'Hide details',
    thinkingText: 'Checking live Binance market data...',
    userRole: 'You',
    agentRole: 'Argus',
    stepCountLabel: 'steps',
    errorNotice: 'Something went wrong while processing your request. Please check your Groq API key and connection.',
    newSessionButton: 'New Chat',
    sessionsLabel: 'Chats',
    defaultSessionTitle: 'New Chat',
    defaultSessionTitles: ['Active Session', 'New Mission', 'Intelligence Session', 'New Chat', 'Chat', 'Active Chat'] as const,
    errorMessageTitle: 'Error',
    newSessionGreeting: (title: string) =>
      `Started a new chat for **${title}**. How can I help you today?`,
  },
  sessions: {
    menuTitle: 'Conversations',
    renameLabel: 'Rename',
    deleteLabel: 'Delete',
    saveLabel: 'Save',
    cancelLabel: 'Cancel',
    renamePlaceholder: 'Chat title...',
    emptyState: 'No conversations yet',
    activeBadge: 'ACTIVE',
    openMenuAria: 'Manage conversations',
  },
  process: {
    title: 'Process',
    thinking: 'Thinking...',
    thinkingWithSeconds: (seconds: number) => `Thinking (${seconds}s)`,
    thoughtForDuration: (seconds: number) =>
      `Thought for ${seconds} ${seconds === 1 ? 'second' : 'seconds'}`,
    workingWithSeconds: (seconds: number) => `Working (${seconds}s)`,
    workedForDuration: (seconds: number) =>
      `Worked for ${seconds} ${seconds === 1 ? 'second' : 'seconds'}`,
    agentWorking: (seconds: number) => `Agent working (${seconds}s)`,
    intermediateUpdateLabel: 'Model update',
    analyzing: 'Analyzing market data...',
    generatingResponse: 'Generating response...',
    toolRunning: 'Running',
    toolCompleted: 'Completed',
    toolFailed: 'Failed',
    toolPrefix: 'Tool',
    stepsCompleted: 'steps completed',
    hideSteps: 'Hide process',
    showSteps: 'Show process',
    finalResponse: 'Final Response',
    thoughtForSteps: 'Thought for',
    reasonedFor: 'Reasoned for',
    thoughtProcess: 'Thought process',
    thinkingProcess: 'Thinking process...',
    thoughts: 'Thoughts',
    toolsUsedHeader: 'tools used',
    singleToolUsed: 'tool used',
    stepSuffix: 'steps',
    successBadge: 'Success',
    viewReasoning: 'View thoughts',
    hideReasoning: 'Hide thoughts',
    toolLabels: {
      get_ticker_price: (symbol?: string) =>
        symbol ? `Checking ${symbol} price` : 'Checking price',
      get_order_book: (symbol?: string) =>
        symbol ? `Inspecting ${symbol} order book depth` : 'Inspecting order book depth',
      get_klines: (symbol?: string, interval?: string) =>
        symbol && interval ? `Reading ${symbol} ${interval} chart` : symbol ? `Reading ${symbol} chart` : 'Reading chart',
      get_24h_stats: (symbol?: string) =>
        symbol ? `Fetching ${symbol} 24h market stats` : 'Fetching 24h market stats',
      get_account_balance: () => 'Checking wallet balances',
      place_spot_order: (symbol?: string, side?: string, quantity?: number) =>
        side && symbol ? `Placing ${side} order for ${quantity ? `${quantity} ` : ''}${symbol}` : 'Placing spot order',
      cancel_order: (symbol?: string) =>
        symbol ? `Cancelling order for ${symbol}` : 'Cancelling order',
      get_funding_rate: (symbol?: string) =>
        symbol ? `Checking ${symbol} funding rate` : 'Checking funding rate',
      get_average_price: (symbol?: string) =>
        symbol ? `Calculating ${symbol} 5m average price` : 'Calculating average price',
      get_recent_trades: (symbol?: string) =>
        symbol ? `Reading ${symbol} recent trade tape` : 'Reading recent trades',
      default: (name: string) => name.replace(/_/g, ' '),
    },
    results: {
      actionSuccess: 'Action completed',
      orderCanceled: 'Order Canceled',
      livePrice: 'Live Price',
      fundingRate: 'Funding Rate',
      annualizedRate: 'Annualized (APR)',
      markPrice: 'Mark Price',
      indexPrice: 'Index Price',
      nextFunding: 'Next Settlement',
      averagePrice: '5m Avg Price',
      recentTrades: 'Recent Trades',
      tradeTime: 'Time',
      takerBuy: 'BUY',
      takerSell: 'SELL',
      buyPressure: 'Taker Buy Ratio',
      spread: 'Spread',
      spreadPercent: 'Spread %',
      bestBid: 'Best Bid',
      bestAsk: 'Best Ask',
      depthImbalance: 'Imbalance Ratio',
      topBids: 'Top Bids',
      topAsks: 'Top Asks',
      high24h: '24h High',
      low24h: '24h Low',
      change24h: '24h Change',
      volume24h: '24h Volume',
      timeframe: 'Timeframe',
      periodChange: 'Period Change',
      latestPrice: 'Latest Price',
      candlesCount: 'Candles Analyzed',
      availableBalance: 'Available',
      lockedBalance: 'In Orders',
      orderStatus: 'Status',
      executedQuantity: 'Quantity',
      executionPrice: 'Executed Price',
      totalQuote: 'Total',
      commission: 'Commission',
      noBalances: 'No active balances found',
      errorTitle: 'Action Error',
      emptyResult: 'No details available',
      priceHeader: 'Price',
      sizeHeader: 'Amount',
    },
    toolNames: {
      get_ticker_price: 'get_ticker_price',
      get_order_book: 'get_order_book',
      get_klines: 'get_klines',
      get_24h_stats: 'get_24h_stats',
      get_funding_rate: 'get_funding_rate',
      get_average_price: 'get_average_price',
      get_recent_trades: 'get_recent_trades',
      get_account_balance: 'get_account_balance',
      place_spot_order: 'place_spot_order',
      cancel_order: 'cancel_order',
    } as Record<string, string>,
  },
} as const;
