import { CATEGORY_DISCOVERY_CONFIG } from '@/lib/8004scan/categories';

const cat = CATEGORY_DISCOVERY_CONFIG;

export const marketplaceContent = {
  marketplace: {
    header: {
      badge: 'ERC-8004 Registry',
      title: 'Agent Marketplace',
      subtitle: (count: number) => `${count.toLocaleString()} agents on BNB Chain`,
      networkBadge: 'BNB Chain (56)',
      liveFeedStatus: 'Live Feed',
      searchPlaceholder: 'Search agents by name, protocol, or token ID...',
      searchClear: 'Clear search query',
      refreshButton: 'Refresh Feed',
      refreshAction: 'Refresh',
      refreshingAction: 'Refreshing...',
      refreshTooltip: 'Fetch latest agents from 8004scan',
    },
    tabs: {
      all: 'All',
      allCategories: 'All Categories',
      yield: cat.yield.label,
      grid: cat.grid.label,
      health: cat.health.label,
      monitoring: cat.monitoring.label,
      payments: cat.payments.label,
      cross_agent: cat.cross_agent.label,
      trading: cat.trading.label,
      derivatives: cat.derivatives.label,
      rebalancing: cat.rebalancing.label,
      liquid_staking: cat.liquid_staking.label,
      research: cat.research.label,
      analytics: cat.analytics.label,
      risk: cat.risk.label,
      infrastructure: cat.infrastructure.label,
      meme_social: cat.meme_social.label,
      cross_chain: cat.cross_chain.label,
      depin_storage: cat.depin_storage.label,
      governance: cat.governance.label,
      categoryBy: 'Category',
      sortBy: 'Sort',
      leaderboard: 'Top Ranked',
      trending: 'Trending',
      featured: 'Featured',
      latest: 'Recently Added',
      newest: 'Newest First',
      primaryPillarsHeader: 'Core Pillars',
      subCategoriesHeader: 'Specialized Domains',
      filterPlaceholder: 'Filter categories...',
      noMatch: 'No matching category',
    },
    card: {
      verified: 'Verified',
      unverified: 'Unverified',
      scoreLabel: 'Score',
      healthLabel: 'Health',
      rankPrefix: 'Rank #',
      x402Badge: 'x402',
      mcpBadge: 'MCP',
      a2aBadge: 'A2A',
      spotlightTag: 'Spotlight',
      inspectAgent: 'Inspect Agent',
      anonymousOwner: 'Anonymous Deployer',
      defaultDescription: 'Autonomous on-chain agent registered under ERC-8004 specification.',
      noProtocols: 'Standard Autonomous Agent',
      activeStatus: 'Active',
    },
    grid: {
      showingRange: (start: number, end: number, total: number) =>
        `Showing ${start}-${end} of ${total.toLocaleString()}`,
      pageIndicator: (current: number, total: number) =>
        `Page ${current} of ${total}`,
      previousPage: 'Previous',
      nextPage: 'Next',
    },
    modal: {
      title: 'Agent Profile & Registry Diagnostics',
      badge: 'ERC-8004 Specification',
      contractAddress: 'Contract Address',
      ownerAddress: 'Deployer / Owner Address',
      ownerEns: 'Owner ENS / Handle',
      registeredAt: 'Registration Date',
      updatedAt: 'Last Telemetry Update',
      supportedProtocols: 'Supported Protocols & Interfaces',
      telemetryTitle: 'On-Chain Performance & Scores',
      totalScore: 'Total Score',
      healthScore: 'Health Factor',
      averageScore: 'Average Rating',
      totalFeedbacks: 'Total User Feedbacks',
      starCount: 'Stars',
      copyAddress: 'Copy Address',
      copiedAddress: 'Copied!',
      viewBscScan: 'View on BscScan',
      view8004Scan: 'View on 8004scan',
      chatPromptAction: 'Analyze in Trading Desk',
      chatPromptText: (name: string, tokenId: string) =>
        `Can you analyze the BNB Chain ERC-8004 agent "${name}" (Token ID #${tokenId})? Detail its architecture, safety score, and on-chain capabilities.`,
      closeModal: 'Close',
    },
    empty: {
      title: 'No Matching Agents Found',
      subtitle: 'No agents matched your search query or selected category filter. Try clearing your search or switching to another category.',
      resetAction: 'Reset Filters',
    },
    error: {
      title: 'Registry Connection Interrupted',
      subtitle: 'Unable to stream live agent data from the 8004scan API endpoints.',
      retryAction: 'Retry Connection',
    },
  },
} as const;
