/**
 * Market search modal, telemetry deck, order book, funding sentinel, and sparkline copy.
 */

export const marketContent = {
  symbolSearch: {
    buttonLabel: 'Search Markets',
    buttonAria: 'Search all Binance USDT markets',
    shortcut: '⌘K',
    shortcutWin: 'Ctrl+K',
    dialogTitle: 'Select Trading Pair',
    dialogSubtitle: 'Browse and switch between active Binance USDT spot markets',
    inputPlaceholder: 'Search pair (e.g. BTC, SOL, PEPE, SUI)...',
    activeBadge: 'ACTIVE',
    emptyTitle: 'No matching pairs found',
    emptySubtitle: 'Try searching with a different ticker or token name.',
    loading: 'Loading symbols...',
    errorMessage: 'Failed to load symbols from Binance API.',
    clearSearch: 'Clear search input',
    closeDialog: 'Close market search',
    marketsCount: (count: number) => `${count} USDT Markets`,
    pairsCount: (count: number) => `${count} pairs`,
    keyboardHint: 'ESC to exit • ↑↓ to navigate • ENTER to select',
    navLegend: '↑↓ navigate',
    selectLegend: '↵ select',
    escLegend: 'esc close',
    loadMoreHint: (remaining: number) => `Scroll down to load ${remaining} more pairs...`,
    showingCount: (visible: number, total: number) => `Showing ${visible} of ${total} pairs`,
  },
  marketPanel: {
    title: 'Market Overview',
    liveBadge: 'LIVE WS',
    streamRateTicker: '1000ms',
    streamRateDepth: '100ms',
    expandPanel: 'Show Market Panel',
    collapsePanel: 'Hide Market Panel',
    statusConnected: 'LIVE WS',
    statusConnecting: 'CONNECTING...',
    statusReconnecting: 'RECONNECTING...',
    statusError: 'OFFLINE',
    loadingTicker: 'Connecting to live ticker...',
    loadingDepth: 'Loading live order book...',
    offlineNotice: 'Market feed disconnected. Attempting to reconnect...',
    tickerTitle: 'Price & 24h Stats',
    orderBookTitle: 'Order Book Depth',
    high24h: '24h High',
    low24h: '24h Low',
    volume24h: '24h Volume',
    volumeQuote: '24h Quote Vol',
    priceChange: '24h Change',
    bestBid: 'Best Bid',
    bestAsk: 'Best Ask',
    spread: 'Spread',
    imbalance: 'Depth Imbalance',
    bids: 'Bids',
    asks: 'Asks',
    priceHeader: 'Price (USDT)',
    sizeHeader: 'Size',
    totalHeader: 'Total',
    bidsRatio: 'Bids',
    asksRatio: 'Asks',
    globalTitle: 'Global Market',
    globalEmptyNotice: 'Select a specific pair in the sidebar to inspect real-time order books and price ticks.',
    mockupNotice: 'Direct Binance WebSocket Feed • sub-100ms ticks',
    streamRateFutures: '1000ms',
    futuresTitle: 'Perpetual Futures Sentinel',
    futuresBadge: 'FUTURES',
    fundingRateLabel: 'Funding Rate',
    fundingCountdownLabel: 'Next Settlement',
    fundingAprLabel: 'Annualized APR',
    markPriceLabel: 'Mark Price',
    indexPriceLabel: 'Index Price',
    basisSpreadLabel: 'Basis (Mark vs Spot)',
    longsPayShorts: 'Longs pay Shorts',
    shortsPayLongs: 'Shorts pay Longs',
    neutralFunding: 'Neutral Rate',
    futuresNotAvailable: 'Perpetual contract not available for this pair',
    loadingFutures: 'Connecting to futures feed...',
    sparklineTitle: '30m Micro Trend',
    sparklineCandles: '1m Candles',
    sparklineHigh: 'H',
    sparklineLow: 'L',
    sparklineLoading: 'Loading trend...',
    tabs: {
      overview: 'Live Telemetry',
      marketData: 'Market Data Agent',
      technicalAnalysis: 'TA Agent',
      riskVolatility: 'Risk Agent',
      sentimentContext: 'Sentiment Agent',
      decision: 'Decision Agent',
      tooltips: {
        overview: 'Live Binance WebSocket streams',
        marketData: 'Agent #1: Live snapshot & quant structure',
        technicalAnalysis: 'Agent #2: Indicators & chart structure (Upcoming)',
        riskVolatility: 'Agent #3: Risk metrics & position sizing (Upcoming)',
        sentimentContext: 'Agent #4: Funding & market mood (Upcoming)',
        decision: 'Agent #5: Final multi-agent synthesis (Upcoming)',
      },
    },
  },
} as const;
