/**
 * Centralized UI text and copy for the Agent Marketplace & Discovery workspace.
 * Strictly adheres to Rule 1: Zero hardcoded text in JSX.
 */

export const marketplaceContent = {
  marketplace: {
    header: {
      badge: 'ERC-8004 Registry',
      title: 'Agent Marketplace',
      subtitle: 'Discover, inspect, and benchmark autonomous AI agents on BNB Chain.',
      networkBadge: 'BNB Chain (56)',
      liveFeedStatus: 'Live 8004scan Feed',
      searchPlaceholder: 'Search by agent name, capability, protocol, contract or token ID...',
      searchClear: 'Clear search query',
      refreshButton: 'Refresh Feed',
      refreshTooltip: 'Fetch latest agents from 8004scan',
      totalRegistered: (count: number) => `${count.toLocaleString()}+ Registered Agents`,
      activeFilterPrefix: 'Filtered by',
    },
    spotlight: {
      sectionTitle: 'Hackathon Spotlights',
      sectionSubtitle: 'Highlighted track architectures & benchmark implementations on BNB Chain',
      badge: 'Official Spotlight',
      hevoTag: 'Rebalancing & Liquidity',
      alphaTag: 'Strategy & Intelligence',
      inspectAction: 'Inspect Architecture',
      benchmarkScore: 'Track A Benchmark',
      collapseSpotlight: 'Hide spotlights',
      expandSpotlight: 'Show spotlights',
    },
    tabs: {
      categoriesTitle: 'Domain Categories',
      feedsTitle: 'Curated Feeds',
      all: 'All Categories',
      yield_optimisation: 'Yield Optimisation',
      grid_trading: 'Grid Trading',
      health_factor: 'Health Factor',
      monitoring: 'Monitoring & Sentinels',
      leaderboard: 'Leaderboard',
      trending: 'Fastest Trending',
      featured: 'Curated Featured',
      latest: 'Recently Registered',
    },
    card: {
      verified: 'Verified',
      unverified: 'Unverified',
      scoreLabel: 'Score',
      healthLabel: 'Health',
      rankPrefix: 'Rank #',
      x402Badge: 'x402 Micropayments',
      mcpBadge: 'MCP Protocol',
      a2aBadge: 'A2A Protocol',
      inspectAgent: 'Inspect Agent',
      anonymousOwner: 'Anonymous Deployer',
      defaultDescription: 'Autonomous on-chain agent registered under ERC-8004 specification.',
      noProtocols: 'Standard Autonomous Agent',
      activeStatus: 'Active',
    },
    grid: {
      showingRange: (start: number, end: number, total: number) =>
        `Showing ${start}–${end} of ${total.toLocaleString()} agents`,
      pageIndicator: (current: number, total: number) =>
        `Page ${current} of ${total}`,
      previousPage: 'Previous',
      nextPage: 'Next',
    },
    modal: {
      title: 'Agent Profile & Registry Diagnostics',
      badge: 'ERC-8004 Specification',
      contractAddress: 'Contract Address',
      ownerAddress: 'Deployer / Owner Address',
      ownerEns: 'Owner ENS / Handle',
      registeredAt: 'Registration Date',
      updatedAt: 'Last Telemetry Update',
      supportedProtocols: 'Supported Protocols & Interfaces',
      telemetryTitle: 'On-Chain Performance & Scores',
      totalScore: 'Total Score',
      healthScore: 'Health Factor',
      averageScore: 'Average Rating',
      totalFeedbacks: 'Total User Feedbacks',
      starCount: 'Stars',
      copyAddress: 'Copy Address',
      copiedAddress: 'Copied!',
      viewBscScan: 'View on BscScan',
      view8004Scan: 'View on 8004scan',
      chatPromptAction: 'Analyze in Trading Desk',
      chatPromptText: (name: string, tokenId: string) =>
        `Can you analyze the BNB Chain ERC-8004 agent "${name}" (Token ID #${tokenId})? Detail its architecture, safety score, and on-chain capabilities.`,
      closeModal: 'Close',
    },
    empty: {
      title: 'No Matching Agents Found',
      subtitle: 'No agents matched your search query or selected category filter. Try clearing your search or switching to another category.',
      resetAction: 'Reset Filters',
    },
    error: {
      title: 'Registry Connection Interrupted',
      subtitle: 'Unable to stream live agent data from the 8004scan API endpoints.',
      retryAction: 'Retry Connection',
    },
    stats: {
      totalAgentsLabel: 'Total Agents',
      categoriesLabel: 'Core Tracks',
      activeChainsLabel: 'Target Chain',
      activeChainsValue: 'BNB Chain (56)',
    },
  },
} as const;
