/**
 * Market search modal, telemetry deck, order book, funding sentinel, and sparkline copy.
 */

export const marketContent = {
  symbolSearch: {
    buttonLabel: 'Search Markets',
    buttonAria: 'Search all Binance USDT markets',
    shortcut: '⌘K',
    shortcutWin: 'Ctrl+K',
    dialogTitle: 'Select Trading Pair',
    dialogSubtitle: 'Browse and switch between active Binance USDT spot markets',
    inputPlaceholder: 'Search pair (e.g. BTC, SOL, PEPE, SUI)...',
    activeBadge: 'ACTIVE',
    emptyTitle: 'No matching pairs found',
    emptySubtitle: 'Try searching with a different ticker or token name.',
    loading: 'Loading symbols...',
    errorMessage: 'Failed to load symbols from Binance API.',
    clearSearch: 'Clear search input',
    closeDialog: 'Close market search',
    marketsCount: (count: number) => `${count} USDT Markets`,
    pairsCount: (count: number) => `${count} pairs`,
    keyboardHint: 'ESC to exit • ↑↓ to navigate • ENTER to select',
    navLegend: '↑↓ navigate',
    selectLegend: '↵ select',
    escLegend: 'esc close',
    loadMoreHint: (remaining: number) => `Scroll down to load ${remaining} more pairs...`,
    showingCount: (visible: number, total: number) => `Showing ${visible} of ${total} pairs`,
  },
  marketPanel: {
    title: 'Market Overview',
    liveBadge: 'LIVE WS',
    streamRateTicker: '1000ms',
    streamRateDepth: '100ms',
    expandPanel: 'Show Market Panel',
    collapsePanel: 'Hide Market Panel',
    statusConnected: 'LIVE WS',
    statusConnecting: 'CONNECTING...',
    statusReconnecting: 'RECONNECTING...',
    statusError: 'OFFLINE',
    loadingTicker: 'Connecting to live ticker...',
    loadingDepth: 'Loading live order book...',
    offlineNotice: 'Market feed disconnected. Attempting to reconnect...',
    tickerTitle: 'Price & 24h Stats',
    orderBookTitle: 'Order Book Depth',
    high24h: '24h High',
    low24h: '24h Low',
    volume24h: '24h Volume',
    volumeQuote: '24h Quote Vol',
    priceChange: '24h Change',
    bestBid: 'Best Bid',
    bestAsk: 'Best Ask',
    spread: 'Spread',
    imbalance: 'Depth Imbalance',
    bids: 'Bids',
    asks: 'Asks',
    priceHeader: 'Price (USDT)',
    sizeHeader: 'Size',
    totalHeader: 'Total',
    bidsRatio: 'Bids',
    asksRatio: 'Asks',
    globalTitle: 'Global Market',
    globalEmptyNotice: 'Select a specific pair in the sidebar to inspect real-time order books and price ticks.',
    mockupNotice: 'Direct Binance WebSocket Feed • sub-100ms ticks',
    streamRateFutures: '1000ms',
    futuresTitle: 'Perpetual Futures Sentinel',
    futuresBadge: 'FUTURES',
    fundingRateLabel: 'Funding Rate',
    fundingCountdownLabel: 'Next Settlement',
    fundingAprLabel: 'Annualized APR',
    markPriceLabel: 'Mark Price',
    indexPriceLabel: 'Index Price',
    basisSpreadLabel: 'Basis (Mark vs Spot)',
    longsPayShorts: 'Longs pay Shorts',
    shortsPayLongs: 'Shorts pay Longs',
    neutralFunding: 'Neutral Rate',
    futuresNotAvailable: 'Perpetual contract not available for this pair',
    loadingFutures: 'Connecting to futures feed...',
    sparklineTitle: '30m Micro Trend',
    sparklineCandles: '1m Candles',
    sparklineHigh: 'H',
    sparklineLow: 'L',
    sparklineLoading: 'Loading trend...',
    tabs: {
      overview: 'Live Telemetry',
      tooltips: {
        overview: 'Live Binance WebSocket streams',
      },
    },
  },
  globalMarket: {
    headerTitle: 'Global Market',
    headerBadge: 'MACRO',
    refreshButton: 'Refresh',
    refreshing: 'Updating...',
    loading: 'Aggregating global market data...',
    errorMessage: 'Unable to query live exchange feeds. Please retry.',
    retryButton: 'Retry',
    lastUpdated: (time: string) => `Updated ${time}`,
    pulseCard: {
      title: 'MARKET PULSE',
      biasLabel: 'Market Bias',
      avgChangeLabel: 'Avg 24h Change',
      riskOn: 'Risk-On',
      mildRiskOn: 'Mildly Risk-On',
      neutral: 'Neutral',
      mildRiskOff: 'Mildly Risk-Off',
      riskOff: 'Risk-Off',
    },
    topMoversCard: {
      title: 'TOP MOVERS',
      gainersLabel: 'Top Gainers',
      losersLabel: 'Top Losers',
      noGainers: 'No gainers recorded',
      noLosers: 'No losers recorded',
    },
    fundingCard: {
      title: 'FUNDING HEATMAP',
      subtitle: 'Major perpetual futures funding rates',
      longsPaying: 'Longs pay',
      shortsPaying: 'Shorts pay',
      neutral: 'Neutral',
      rateHeader: 'Rate',
      aprHeader: 'APR',
      biasHeader: 'Payer',
    },
    positioningCard: {
      title: 'MACRO POSITIONING',
      retailLabel: 'Retail Sentiment (BTC + ETH)',
      whalesLabel: 'Whale Positioning (BTC + ETH)',
      ratioLabel: 'L/S Ratio',
      longBiased: 'Long-biased',
      shortBiased: 'Short-biased',
      neutral: 'Neutral',
    },
  },
} as const;
