/**
 * Agent reasoning process, execution steps, tool labels, and tool results copy.
 */

export const processContent = {
  process: {
    title: 'Process',
    thinking: 'Thinking...',
    thinkingWithSeconds: (seconds: number) => `Thinking (${seconds}s)`,
    thoughtForDuration: (seconds: number) =>
      `Thought for ${seconds} ${seconds === 1 ? 'second' : 'seconds'}`,
    workingWithSeconds: (seconds: number) => `Working (${seconds}s)`,
    workedForDuration: (seconds: number) =>
      `Worked for ${seconds} ${seconds === 1 ? 'second' : 'seconds'}`,
    agentWorking: (seconds: number) => `Agent working (${seconds}s)`,
    intermediateUpdateLabel: 'Model update',
    analyzing: 'Analyzing market data...',
    generatingResponse: 'Generating response...',
    toolRunning: 'Running',
    toolCompleted: 'Completed',
    toolFailed: 'Failed',
    toolPrefix: 'Tool',
    stepsCompleted: 'steps completed',
    hideSteps: 'Hide process',
    showSteps: 'Show process',
    finalResponse: 'Final Response',
    thoughtForSteps: 'Thought for',
    reasonedFor: 'Reasoned for',
    thoughtProcess: 'Thought process',
    thinkingProcess: 'Thinking process...',
    thoughts: 'Thoughts',
    toolsUsedHeader: 'tools used',
    singleToolUsed: 'tool used',
    stepSuffix: 'steps',
    successBadge: 'Success',
    viewReasoning: 'View thoughts',
    hideReasoning: 'Hide thoughts',
    toolLabels: {
      get_ticker_price: (symbol?: string) =>
        symbol ? `Checking ${symbol} price` : 'Checking price',
      get_order_book: (symbol?: string) =>
        symbol ? `Inspecting ${symbol} order book depth` : 'Inspecting order book depth',
      get_klines: (symbol?: string, interval?: string) =>
        symbol && interval ? `Reading ${symbol} ${interval} chart` : symbol ? `Reading ${symbol} chart` : 'Reading chart',
      get_24h_stats: (symbol?: string) =>
        symbol ? `Fetching ${symbol} 24h market stats` : 'Fetching 24h market stats',
      get_funding_rate: (symbol?: string) =>
        symbol ? `Checking ${symbol} funding rate` : 'Checking funding rate',
      get_average_price: (symbol?: string) =>
        symbol ? `Calculating ${symbol} 5m average price` : 'Calculating average price',
      get_recent_trades: (symbol?: string) =>
        symbol ? `Reading ${symbol} recent trade tape` : 'Reading recent trades',
      get_open_interest: (symbol?: string) =>
        symbol ? `Checking ${symbol} open interest` : 'Checking open interest',
      get_global_long_short_ratio: (symbol?: string) =>
        symbol ? `Checking ${symbol} global long/short account ratio` : 'Checking global long/short account ratio',
      get_top_long_short_ratio: (symbol?: string) =>
        symbol ? `Checking ${symbol} top trader position ratio` : 'Checking top trader position ratio',
      search_crypto_news: (symbol?: string) =>
        symbol ? `Searching latest ${symbol} news & catalysts` : 'Searching crypto news & catalysts',
      default: (name: string) => name.replace(/_/g, ' '),
    },
    results: {
      actionSuccess: 'Action completed',
      livePrice: 'Live Price',
      fundingRate: 'Funding Rate',
      annualizedRate: 'Annualized (APR)',
      markPrice: 'Mark Price',
      indexPrice: 'Index Price',
      nextFunding: 'Next Settlement',
      averagePrice: '5m Avg Price',
      recentTrades: 'Recent Trades',
      tradeTime: 'Time',
      takerBuy: 'BUY',
      takerSell: 'SELL',
      buyPressure: 'Taker Buy Ratio',
      openInterest: 'Open Interest',
      openInterestContracts: 'Contracts',
      openInterestValue: 'Notional Value',
      openInterestTime: 'Updated',
      spread: 'Spread',
      spreadPercent: 'Spread %',
      bestBid: 'Best Bid',
      bestAsk: 'Best Ask',
      depthImbalance: 'Imbalance Ratio',
      topBids: 'Top Bids',
      topAsks: 'Top Asks',
      high24h: '24h High',
      low24h: '24h Low',
      change24h: '24h Change',
      volume24h: '24h Volume',
      timeframe: 'Timeframe',
      periodChange: 'Period Change',
      latestPrice: 'Latest Price',
      candlesCount: 'Candles Analyzed',
      newsResults: 'Web News & Catalysts',
      newsArticlesFound: 'Articles Found',
      newsSource: 'Source',
      newsDate: 'Date',
      newsOpenArticle: 'Read article',
      longShortRatio: 'Long/Short Ratio',
      longAccountRatio: 'Long Accounts',
      shortAccountRatio: 'Short Accounts',
      topLongRatio: 'Whale Longs',
      topShortRatio: 'Whale Shorts',
      retailSentiment: 'Account Sentiment',
      whaleSentiment: 'Whale Position Sentiment',
      bullishBias: 'BULLISH',
      bearishBias: 'BEARISH',
      neutralBias: 'NEUTRAL',
      period: 'Period',
      errorTitle: 'Action Error',
      emptyResult: 'No details available',
      priceHeader: 'Price',
      sizeHeader: 'Amount',
    },
    toolNames: {
      get_ticker_price: 'get_ticker_price',
      get_order_book: 'get_order_book',
      get_klines: 'get_klines',
      get_24h_stats: 'get_24h_stats',
      get_funding_rate: 'get_funding_rate',
      get_average_price: 'get_average_price',
      get_recent_trades: 'get_recent_trades',
      get_open_interest: 'get_open_interest',
      get_global_long_short_ratio: 'get_global_long_short_ratio',
      get_top_long_short_ratio: 'get_top_long_short_ratio',
      search_crypto_news: 'search_crypto_news',
    } as Record<string, string>,
  },
} as const;
