/**
 * Dedicated sub-agents, quant snapshot metrics, role personalities, and schema copy.
 */

export const subAgentsContent = {
  subAgents: {
    headerButtonLabel: 'Sub-Agents',
    headerButtonTooltip: 'Open Dedicated Sub-Agents in Right Panel',
    agentActiveBadge: 'ACTIVE',
    agentBadgeNum: '#1',
    marketData: {
      name: 'Market Data Agent',
      role: 'Live Snapshot & Quant Specialist',
      personality: 'Pure Quant & Live Endpoints',
      statusReady: 'READY',
      statusRunning: 'COMPUTING...',
      statusLive: 'LIVE SNAPSHOT',
      refreshButton: 'Run Quant Snapshot',
      refreshing: 'Analyzing feeds...',
      lastUpdated: (time: string) => `Updated at ${time}`,
      metrics: {
        biasLabel: 'Market Bias',
        confidenceLabel: 'Quant Confidence',
        volatilityLabel: 'Volatility Tier',
        liquidityLabel: 'Liquidity Score',
        keyLevelsTitle: 'Key Quant Levels',
        supportLabel: 'Support (S1)',
        pivotLabel: '24h Pivot',
        resistanceLabel: 'Resistance (R1)',
        orderBookTitle: 'Order Book Microstructure',
        depthRatioLabel: 'Bid/Ask Depth Ratio',
        bidVolumeLabel: 'Bid Depth (20L)',
        askVolumeLabel: 'Ask Depth (20L)',
        spreadLabel: 'Spread',
        spreadRating: 'Tight Spread',
        vwapBenchmarkTitle: '5m VWAP & Tape Flow',
        vwapDeviationLabel: 'VWAP Deviation',
        vwapAbove: 'Above 5m VWAP (Premium)',
        vwapBelow: 'Below 5m VWAP (Discount)',
        takerFlowLabel: 'Taker Flow (Aggression)',
        takerBuy: 'Taker Buy',
        takerSell: 'Taker Sell',
        synthesisTitle: 'Agent Analytical Takeaway',
        jsonDrawerTitle: 'Structured JSON Payload',
        jsonDrawerSubtitle: 'Generated via strict Zod schema for machine-readable UI binding',
        copyJson: 'Copy JSON',
        copiedJson: 'Copied!',
        viewJson: 'View Structured JSON',
        hideJson: 'Hide JSON',
      },
      mockValues: {
        bias: 'BULLISH' as const,
        confidence: 86,
        volatility: 'NORMAL' as const,
        liquidity: 94,
        bidRatio: 59,
        askRatio: 41,
        depthImbalance: '1.44x',
        spreadUsd: '0.01',
        spreadBps: '0.007%',
        vwapDev: '+0.38%',
        takerBuyPercent: 62.4,
        takerSellPercent: 37.6,
        takeaway: (symbol: string) =>
          `Bids outweigh asks 1.44:1 across top 20 levels with decisive buyer aggression (62.4% taker buy volume). ${symbol} is sustaining a +0.38% premium above the 5m rolling VWAP, holding strong near-term support.`,
      },
    },
  },
} as const;
