export const AGENT_TOOL_DESCRIPTIONS = {
  getTickerPrice: 'Fetch the real-time ticker price for a Binance trading pair (e.g. SOLUSDT, BTCUSDT, ETHUSDT). MUST be called before stating or reporting the price of any symbol.',
  getOrderBook: 'Fetch the live order book depth (top bids and asks) to evaluate liquidity and compute slippage. MUST be called before reporting order book state or depth.',
  getKlines: 'Fetch historical candlestick (kline) data to evaluate trend direction, RSI, and exponential moving averages. MUST be called before reporting technical trend data.',
  get24hStats: 'Fetch 24-hour price statistics including 24h high, low, price change percentage, and quote volume. MUST be called before reporting 24h performance or metrics.',
  getFundingRate: 'Fetch the real-time perpetual futures funding rate, mark price, and next settlement time for a trading pair. Essential for derivative sentiment, funding cost, and long/short positioning.',
  getOpenInterest: 'Fetch real-time perpetual futures open interest to evaluate market positioning, leverage buildup, and liquidation risk.',
  getTopLongShortRatio: 'Fetch top 20% whale trader long vs. short position ratio for a Binance Futures pair. Essential for smart money tracking and whale vs retail divergence.',
  searchCryptoNews: 'Search live cryptocurrency news, catalysts, regulatory events, narrative shifts, and market sentiment via Exa AI. Supports optional category focus ("news", "company", "financial report", "research paper"), ISO 8601 date range filters (startPublishedDate/endPublishedDate), and domain restrictions. Call whenever the user asks for news, catalysts, reasons for price movements, or protocol roadmaps.',
  getAgentTelemetry: 'Inspect real-time on-chain telemetry, total score, health factor %, owner ENS/address, supported protocols (x402, MCP, A2A), and contract verification for a specific ERC-8004 autonomous agent on BNB Chain by Token ID or name. MUST be called whenever the user asks to analyze, diagnose, or inspect a specific ERC-8004 agent or clicks "Analyze in Trading Desk".',
  searchAgentMarketplace: 'Search and discover autonomous AI agents registered under the ERC-8004 specification on BNB Chain (BSC Chain ID 56). Filter by search keywords, ecosystem category (yield, grid, health, rebalancing, trading, risk, etc.), and sort order. Call whenever the user asks to find, compare, recommend, or benchmark agents across the marketplace.',
} as const;
